soc/soc_bus_v0.sv
soc/soc_top_v0.sv
periphs/mem_itcm.sv
periphs/uart.v
periphs/mem_dtcm.sv
core/exu_bru.sv
core/exu.sv
core/regfile.sv
core/mau.sv
core/exu_csr.sv
core/wbu.sv
core/exu_lsu.sv
core/exu_alu.sv
core/csr_regs.sv
core/ifu.sv
core/ctrl_hazard.sv
core/core_rv32i_v0.sv
core/idu.sv
