`define IMEM_DEPTH 4096
`define ZERO_WORD 32'b0

`define RFIDX_WIDTH 5

`define XWIDTH 32   // RV32, regfile width is 32

// ===========================================================================
// Decode relevant macro, E203v2 as a reference.

// ---- decinfo_bus
`define DECINFO_GRP_WIDTH           3
`define DECINFO_GRP_ALU             `DECINFO_GRP_WIDTH'd0
`define DECINFO_GRP_LSU             `DECINFO_GRP_WIDTH'd1
`define DECINFO_GRP_BRU             `DECINFO_GRP_WIDTH'd2
`define DECINFO_GRP_CSR             `DECINFO_GRP_WIDTH'd3

    `define DECINFO_GRP_LSB         0
    `define DECINFO_GRP_MSB         (`DECINFO_GRP_LSB + `DECINFO_GRP_WIDTH -1)
`define DECINFO_GRP         `DECINFO_GRP_MSB :`DECINFO_GRP_LSB

`define DECINFO_SUBDECINFO_LSB  (`DECINFO_GRP_MSB +1)

// ----------------        ALU group        ---------------- //
    `define DECINFO_ALU_ADD_LSB     `DECINFO_SUBDECINFO_LSB
    `define DECINFO_ALU_ADD_MSB     (`DECINFO_ALU_ADD_LSB+1-1)
`define DECINFO_ALU_ADD     `DECINFO_ALU_ADD_MSB :`DECINFO_ALU_ADD_LSB
    `define DECINFO_ALU_SUB_LSB     (`DECINFO_ALU_ADD_MSB+1)
    `define DECINFO_ALU_SUB_MSB     (`DECINFO_ALU_SUB_LSB+1-1)
`define DECINFO_ALU_SUB     `DECINFO_ALU_SUB_MSB :`DECINFO_ALU_SUB_LSB
    `define DECINFO_ALU_SLL_LSB     (`DECINFO_ALU_SUB_MSB+1)
    `define DECINFO_ALU_SLL_MSB     (`DECINFO_ALU_SLL_LSB+1-1)
`define DECINFO_ALU_SLL     `DECINFO_ALU_SLL_MSB :`DECINFO_ALU_SLL_LSB
    `define DECINFO_ALU_SLT_LSB     (`DECINFO_ALU_SLL_MSB+1)
    `define DECINFO_ALU_SLT_MSB     (`DECINFO_ALU_SLT_LSB+1-1)
`define DECINFO_ALU_SLT     `DECINFO_ALU_SLT_MSB :`DECINFO_ALU_SLT_LSB
    `define DECINFO_ALU_SLTU_LSB    (`DECINFO_ALU_SLT_MSB+1)
    `define DECINFO_ALU_SLTU_MSB    (`DECINFO_ALU_SLTU_LSB+1-1)
`define DECINFO_ALU_SLTU    `DECINFO_ALU_SLTU_MSB:`DECINFO_ALU_SLTU_LSB
    `define DECINFO_ALU_XOR_LSB     (`DECINFO_ALU_SLTU_MSB+1)
    `define DECINFO_ALU_XOR_MSB     (`DECINFO_ALU_XOR_LSB+1-1)
`define DECINFO_ALU_XOR     `DECINFO_ALU_XOR_MSB :`DECINFO_ALU_XOR_LSB
    `define DECINFO_ALU_SRL_LSB     (`DECINFO_ALU_XOR_MSB+1)
    `define DECINFO_ALU_SRL_MSB     (`DECINFO_ALU_SRL_LSB+1-1)
`define DECINFO_ALU_SRL     `DECINFO_ALU_SRL_MSB :`DECINFO_ALU_SRL_LSB
    `define DECINFO_ALU_SRA_LSB     (`DECINFO_ALU_SRL_MSB+1)
    `define DECINFO_ALU_SRA_MSB     (`DECINFO_ALU_SRA_LSB+1-1)
`define DECINFO_ALU_SRA     `DECINFO_ALU_SRA_MSB :`DECINFO_ALU_SRA_LSB
    `define DECINFO_ALU_OR_LSB      (`DECINFO_ALU_SRA_MSB+1)
    `define DECINFO_ALU_OR_MSB      (`DECINFO_ALU_OR_LSB+1-1)
`define DECINFO_ALU_OR      `DECINFO_ALU_OR_MSB  :`DECINFO_ALU_OR_LSB
    `define DECINFO_ALU_AND_LSB     (`DECINFO_ALU_OR_MSB+1)
    `define DECINFO_ALU_AND_MSB     (`DECINFO_ALU_AND_LSB+1-1)
`define DECINFO_ALU_AND     `DECINFO_ALU_AND_MSB :`DECINFO_ALU_AND_LSB // Above: R-type, I-type-arithm
    `define DECINFO_ALU_LUI_LSB     (`DECINFO_ALU_AND_MSB+1)
    `define DECINFO_ALU_LUI_MSB     (`DECINFO_ALU_LUI_LSB+1-1)
`define DECINFO_ALU_LUI     `DECINFO_ALU_LUI_MSB :`DECINFO_ALU_LUI_LSB // U-type
    `define DECINFO_ALU_OP1PC_LSB   (`DECINFO_ALU_LUI_MSB+1)
    `define DECINFO_ALU_OP1PC_MSB   (`DECINFO_ALU_OP1PC_LSB+1-1)
`define DECINFO_ALU_OP1PC   `DECINFO_ALU_OP1PC_MSB :`DECINFO_ALU_OP1PC_LSB
    `define DECINFO_ALU_OP2IMM_LSB    (`DECINFO_ALU_OP1PC_MSB+1)
    `define DECINFO_ALU_OP2IMM_MSB    (`DECINFO_ALU_OP2IMM_LSB+1-1)
`define DECINFO_ALU_OP2IMM    `DECINFO_ALU_OP2IMM_MSB :`DECINFO_ALU_OP2IMM_LSB

`define DECINFO_BUS_ALU_WIDTH   (`DECINFO_ALU_OP2IMM_MSB+1)

//     `define DECINFO_ALU_NOP_LSB    (`DECINFO_ALU_OP1PC_MSB+1)
//     `define DECINFO_ALU_NOP_MSB    (`DECINFO_ALU_NOP_LSB+1-1)
// `define DECINFO_ALU_NOP    `DECINFO_ALU_NOP_MSB :`DECINFO_ALU_NOP_LSB 
//     `define DECINFO_ALU_ECAL_LSB  (`DECINFO_ALU_NOP_MSB+1)
//     `define DECINFO_ALU_ECAL_MSB  (`DECINFO_ALU_ECAL_LSB+1-1)
// `define DECINFO_ALU_ECAL   `DECINFO_ALU_ECAL_MSB:`DECINFO_ALU_ECAL_LSB 
//     `define DECINFO_ALU_EBRK_LSB  (`DECINFO_ALU_ECAL_MSB+1)
//     `define DECINFO_ALU_EBRK_MSB  (`DECINFO_ALU_EBRK_LSB+1-1)
// `define DECINFO_ALU_EBRK   `DECINFO_ALU_EBRK_MSB:`DECINFO_ALU_EBRK_LSB 
//     `define DECINFO_ALU_WFI_LSB  (`DECINFO_ALU_EBRK_MSB+1)
//     `define DECINFO_ALU_WFI_MSB  (`DECINFO_ALU_WFI_LSB+1-1)
// `define DECINFO_ALU_WFI   `DECINFO_ALU_WFI_MSB:`DECINFO_ALU_WFI_LSB 


// ----------------        LSU group        ---------------- //
    `define DECINFO_LSU_LOAD_LSB    `DECINFO_SUBDECINFO_LSB
    `define DECINFO_LSU_LOAD_MSB    (`DECINFO_LSU_LOAD_LSB+1-1)
`define DECINFO_LSU_LOAD    `DECINFO_LSU_LOAD_MSB :`DECINFO_LSU_LOAD_LSB
    `define DECINFO_LSU_STORE_LSB   (`DECINFO_LSU_LOAD_MSB+1)
    `define DECINFO_LSU_STORE_MSB   (`DECINFO_LSU_STORE_LSB+1-1)
`define DECINFO_LSU_STORE   `DECINFO_LSU_STORE_MSB :`DECINFO_LSU_STORE_LSB
    `define DECINFO_LSU_SIZE_LSB    (`DECINFO_LSU_STORE_MSB+1)
    `define DECINFO_LSU_SIZE_MSB    (`DECINFO_LSU_SIZE_LSB+2-1)
`define DECINFO_LSU_SIZE    `DECINFO_LSU_SIZE_MSB :`DECINFO_LSU_SIZE_LSB
    `define DECINFO_LSU_USIGN_LSB   (`DECINFO_LSU_SIZE_MSB+1)
    `define DECINFO_LSU_USIGN_MSB   (`DECINFO_LSU_USIGN_LSB+1-1)
`define DECINFO_LSU_USIGN    `DECINFO_LSU_USIGN_MSB :`DECINFO_LSU_USIGN_LSB
    `define DECINFO_LSU_OP2IMM_LSB  (`DECINFO_LSU_USIGN_MSB+1)
    `define DECINFO_LSU_OP2IMM_MSB  (`DECINFO_LSU_OP2IMM_LSB+1-1)
`define DECINFO_LSU_OP2IMM  `DECINFO_LSU_OP2IMM_MSB :`DECINFO_LSU_OP2IMM_LSB

`define DECINFO_BUS_LSU_WIDTH   (`DECINFO_LSU_OP2IMM_MSB+1)



// ----------------        BRU group        ---------------- //

`define DECINFO_BUS_BRU_WIDTH   3



`define DECINFO_BUS_WIDTH       `DECINFO_BUS_ALU_WIDTH