set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[7]}]
set_property PACKAGE_PIN F13 [get_ports {ad_data[0]}]
set_property PACKAGE_PIN F14 [get_ports {ad_data[1]}]
set_property PACKAGE_PIN E13 [get_ports {ad_data[2]}]
set_property PACKAGE_PIN E14 [get_ports {ad_data[3]}]
set_property PACKAGE_PIN F16 [get_ports {ad_data[4]}]
set_property PACKAGE_PIN E17 [get_ports {ad_data[5]}]
set_property PACKAGE_PIN C13 [get_ports {ad_data[6]}]
set_property PACKAGE_PIN B13 [get_ports {ad_data[7]}]
set_property PACKAGE_PIN D16 [get_ports ad_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk]
set_property PACKAGE_PIN U7 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN V4 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN W21 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property PACKAGE_PIN T20 [get_ports uart_rxd]

#set_property CFGBVS VCCO [current_design]
#set_property CONFIG_VOLTAGE 3.3 [current_design]
#set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
#set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
#set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
#set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]

#set_property IOSTANDARD LVCMOS15 [get_ports {key[1]}]
#set_property IOSTANDARD LVCMOS15 [get_ports {key[0]}]
#set_property PACKAGE_PIN T3 [get_ports {key[1]}]
#set_property PACKAGE_PIN T4 [get_ports {key[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports CS]
set_property IOSTANDARD LVCMOS33 [get_ports PDC]
set_property IOSTANDARD LVCMOS33 [get_ports PS0]
set_property IOSTANDARD LVCMOS33 [get_ports PS1]
set_property IOSTANDARD LVCMOS33 [get_ports PS2]
set_property IOSTANDARD LVCMOS33 [get_ports PS3]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO0]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO1]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO2]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO3]
set_property IOSTANDARD LVCMOS33 [get_ports UPDATE]

set_property PACKAGE_PIN M21 [get_ports PDC]
set_property PACKAGE_PIN N22 [get_ports Reset]
set_property PACKAGE_PIN N20 [get_ports UPDATE]
set_property PACKAGE_PIN L19 [get_ports CS]
set_property PACKAGE_PIN J22 [get_ports SCLK]
set_property PACKAGE_PIN J20 [get_ports SDIO3]
set_property PACKAGE_PIN G20 [get_ports PS0]
set_property PACKAGE_PIN L21 [get_ports PS1]
set_property PACKAGE_PIN M22 [get_ports PS2]
set_property PACKAGE_PIN M20 [get_ports PS3]
set_property PACKAGE_PIN L20 [get_ports SDIO0]
set_property PACKAGE_PIN H22 [get_ports SDIO1]
set_property PACKAGE_PIN J21 [get_ports SDIO2]




