# xc7a200tfbg484-2
set_property PACKAGE_PIN R4 [get_ports clk]
set_property IOSTANDARD LVCMOS15 [get_ports clk]
set_property PACKAGE_PIN U7 [get_ports rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports rst_n]

create_clock -period 20.000 -name clk [get_ports clk]

# UART
set_property PACKAGE_PIN D17 [get_ports o_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports o_uart_tx]
set_property PACKAGE_PIN E14 [get_ports i_uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports i_uart_rx]

# set_property PACKAGE_PIN D17 [get_ports uart_txd]
# set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
# set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
# set_property PACKAGE_PIN E14 [get_ports uart_rxd]

# # ADC
# set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[7]}]
# set_property PACKAGE_PIN D16 [get_ports {ad_data[0]}]
# set_property PACKAGE_PIN E16 [get_ports {ad_data[1]}]
# set_property PACKAGE_PIN D15 [get_ports {ad_data[2]}]
# set_property PACKAGE_PIN D14 [get_ports {ad_data[3]}]
# set_property PACKAGE_PIN A21 [get_ports {ad_data[4]}]
# set_property PACKAGE_PIN B21 [get_ports {ad_data[5]}]
# set_property PACKAGE_PIN C22 [get_ports {ad_data[6]}]
# set_property PACKAGE_PIN B22 [get_ports {ad_data[7]}]
# set_property PACKAGE_PIN D20 [get_ports ad_clk]
# set_property IOSTANDARD LVCMOS33 [get_ports ad_clk]

# # DDS
# set_property IOSTANDARD LVCMOS33 [get_ports CS]
# set_property IOSTANDARD LVCMOS33 [get_ports PDC]
# set_property IOSTANDARD LVCMOS33 [get_ports PS0]
# set_property IOSTANDARD LVCMOS33 [get_ports PS1]
# set_property IOSTANDARD LVCMOS33 [get_ports PS2]
# set_property IOSTANDARD LVCMOS33 [get_ports PS3]
# set_property IOSTANDARD LVCMOS33 [get_ports Reset]
# set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
# set_property IOSTANDARD LVCMOS33 [get_ports SDIO0]
# set_property IOSTANDARD LVCMOS33 [get_ports SDIO1]
# set_property IOSTANDARD LVCMOS33 [get_ports SDIO2]
# set_property IOSTANDARD LVCMOS33 [get_ports SDIO3]
# set_property IOSTANDARD LVCMOS33 [get_ports UPDATE]
# set_property PACKAGE_PIN Y13  [get_ports PDC]
# set_property PACKAGE_PIN Y16  [get_ports Reset]
# set_property PACKAGE_PIN AB12 [get_ports UPDATE]
# set_property PACKAGE_PIN W12  [get_ports CS]
# set_property PACKAGE_PIN AB13 [get_ports SCLK]
# set_property PACKAGE_PIN AA14 [get_ports SDIO3]
# set_property PACKAGE_PIN AB16 [get_ports PS0]
# set_property PACKAGE_PIN AA13 [get_ports PS1]
# set_property PACKAGE_PIN AB15 [get_ports PS2]
# set_property PACKAGE_PIN AB17 [get_ports PS3]
# set_property PACKAGE_PIN AA16 [get_ports SDIO0]
# set_property PACKAGE_PIN W11  [get_ports SDIO1]
# set_property PACKAGE_PIN AA15 [get_ports SDIO2]




