"""
gen_lint_filelist.py
--------------------
Generates `.vscode/lint_filelist.f` for iverilog linting in VS Code.

Output paths are RELATIVE to the workspace root (the directory containing
.vscode/), so the filelist is portable across machines without any edits.

Usage (run from anywhere inside the project):
    python .vscode/gen_lint_filelist.py

Configuration:
    Edit the RTL_DIRS, TB_DIRS, and INC_DIRS lists below to add/remove
    search directories when the project structure changes.
"""

import os
import sys

# ---------------------------------------------------------------------------
# Configuration -- edit these when the project structure changes
# ---------------------------------------------------------------------------

# Top-level RTL directories to scan recursively for .v / .sv files.
# Paths are relative to the workspace root.
RTL_DIRS = [
    "de_rtl/v0_rv32i_basic/core",
    "de_rtl/v0_rv32i_basic/periphs",
    "de_rtl/v0_rv32i_basic/soc",
]

# Testbench directories (also scanned recursively).
TB_DIRS = [
    "dv_tb",
]

# +incdir+ entries for `include resolution (relative to workspace root).
INC_DIRS = [
    "de_rtl/v0_rv32i_basic/defines",
]

# Subdirectory names to skip during scanning (e.g. defines already covered
# by INC_DIRS above, or any directories with non-synthesisable helpers).
SKIP_DIRS = {"defines"}

# Output filelist path, relative to workspace root.
OUTPUT_FILE = ".vscode/lint_filelist.f"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_workspace_root():
    """Walk up from this script's location until we find the .vscode dir."""
    # This script lives in <workspace>/.vscode/, so the workspace root is
    # simply the parent of the directory containing this script.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    # script_dir is already .vscode/; parent is workspace root.
    root = os.path.dirname(script_dir)
    if not os.path.isdir(os.path.join(root, ".vscode")):
        # Fallback: search upward from CWD
        cur = os.path.abspath(os.getcwd())
        while True:
            if os.path.isdir(os.path.join(cur, ".vscode")):
                return cur
            parent = os.path.dirname(cur)
            if parent == cur:
                print("Error: Could not locate workspace root (.vscode not found).")
                sys.exit(1)
            cur = parent
    return root


def collect_verilog_files(root, rel_dirs, skip_dirs):
    """Return a list of paths (relative to root, forward-slash) for all
    .v / .sv files found under the given relative directories."""
    found = []
    for rel_dir in rel_dirs:
        abs_dir = os.path.join(root, *rel_dir.split("/"))
        if not os.path.isdir(abs_dir):
            print(f"  [WARN] Directory not found, skipping: {rel_dir}")
            continue
        for dirpath, dirnames, filenames in os.walk(abs_dir):
            # Prune skip_dirs in-place so os.walk won't descend into them
            dirnames[:] = [d for d in dirnames if d not in skip_dirs]
            for fname in filenames:
                if fname.endswith(".v") or fname.endswith(".sv"):
                    abs_path = os.path.join(dirpath, fname)
                    rel_path = os.path.relpath(abs_path, root).replace("\\", "/")
                    if rel_path not in found:
                        found.append(rel_path)
    return found


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    root = find_workspace_root()
    print(f"Workspace root : {root}")

    tb_files  = collect_verilog_files(root, TB_DIRS,  skip_dirs=set())
    rtl_files = collect_verilog_files(root, RTL_DIRS, skip_dirs=SKIP_DIRS)

    output_abs = os.path.join(root, *OUTPUT_FILE.split("/"))
    os.makedirs(os.path.dirname(output_abs), exist_ok=True)

    with open(output_abs, "w", encoding="utf-8") as fout:
        fout.write("// Auto-generated by .vscode/gen_lint_filelist.py\n")
        fout.write("// Paths are relative to the workspace root.\n")
        fout.write("// Re-run the script whenever RTL files are added or removed.\n")
        fout.write("//\n")

        # +incdir+ entries
        for inc in INC_DIRS:
            abs_inc = os.path.join(root, *inc.split("/"))
            if os.path.isdir(abs_inc):
                fout.write(f"+incdir+{inc}\n")
            else:
                print(f"  [WARN] Include dir not found, skipping: {inc}")

        fout.write("\n")

        # TB files first, then RTL
        all_files = tb_files + rtl_files
        for f in all_files:
            fout.write(f + "\n")

    total = len(all_files)
    print(f"Generated      : {OUTPUT_FILE}  ({total} files)")
    print(f"  TB  files    : {len(tb_files)}")
    print(f"  RTL files    : {len(rtl_files)}")


if __name__ == "__main__":
    main()
