soc/soc_top.sv
soc/soc_bus.sv
periphs/backing_imem.sv
periphs/uart.v
periphs/mem_dtcm.sv
core/core.sv
core/icache.sv
core/branch_predictor.sv
core/ras_dual_full_stack.sv
core/ifu.sv
core/idu.sv
core/exu.sv
core/exu_alu.sv
core/exu_bru.sv
core/exu_lsu.sv
core/exu_csr.sv
core/exu_muldiv.sv
core/mul_radix2.sv
core/mul_fast17.sv
core/div_radix2.sv
core/mau.sv
core/wbu.sv
core/regfile.sv
core/ctrl_hazard.sv
core/csr_regs.sv
